#!/usr/bin/env bash
sudo apt-get update -y
sudo apt-get install nginx -y

# Add custom header configuration to Nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        add_header X-Served-By $hostname;
        root /var/www/html;
        index index.html;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx start
